version: "3"
services:
  springboot-app:
    container_name: c1 
    image: employee
    restart: always
    build: .
    ports:
        - 8091:8090
    environment: 
      MYSQL_HOST: mysqldb3
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  c1:
    container_name: mysqldb3
    image: mysql
  
    ports:
       - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root   